Добавляет настройку Service Workers
malcewdeveloper/lazer-overload-yp pull request #60
Opened 2024-09-01 20:02 UTC by malcewdeveloper

### Какую задачу решаем
- добавляет файл sw.js с кастройкой кеширования приложения

### Что нового
- создал базовую настройку для кеширования веб-приложения

### Что можно улучшить
- добавить кастомную страницу с ошибкой в случае неуспешных запросов на сервер
- добавить качественную обработку запросов, чтобы бы при обновлении не скидывало на страницу входа.

### Скриншоты/видяшка (если есть)

https://github.com/user-attachments/assets/93fcbe10-1c03-47c7-95ea-83d9e155a898

2024-09-07 20:14 UTC, chedore approved these changes

2024-09-08 11:21 UTC, kyzinatra commented on packages/client/sw.js
> +
Надо исправить: service worker не умеет кэшировать `ts, tsx` файлы, так как они не существуют в контексте браузера, это значит, что сборщик собирает все файлы, обрабатывает и выдает `html, css, js` файлы. Только их может обработать браузер и никакие другое. Вам необходимо получить названия этих файлов а также всей статики (картинок и подобного) и вписать их сюда. Учтите, что при каждой сборке названия файлов будут разными, поэтому их нужно будет получать тоже в процессе сборки или запуска. Вы можете воспользоваться готовыми инструментами или написать свое решение

2024-09-08 11:23 UTC, kyzinatra commented on packages/client/sw.js
> +                    if (
Отлично! Хорошая реализация кэша, но стоит немного оптимизировать его, чтобы инвалидировать кэш по таймеру и не кэшировать рессурсы, которые того не требуют (к примеру отправка сообщения) и также всю статику. Она должна кэшироваться в `install`

2024-09-08 11:26 UTC, kyzinatra requested changes
Отличная работа! Вы хорошо реализовали подключение сокетов, но стоит еще немного над ними поработать, чтобы они правильно кэшировали все рессурсы в `install`, а в идеале, чтобы `fetch` не кэшировал все без разбора, а только то, что правда имеет смысл закэшировать.

2024-09-12 00:20 UTC, malcewdeveloper commented
@kyzinatra Привет! 
Прислушался к твоим рекомендациям, копался в интернете, в ChatGPT, испробовал кучу вариантов реализации и написания кастомных плагинов для Vite.
Все сводится к одну готовому решению:
`vite-plugin-pwa`, который создает файл манифеста и по совместительсвту из этого же файла сам генерирует sw.js, где настраиват кеширование на статические файлы.

2024-09-12 05:36 UTC, kyzinatra commented
> @kyzinatra Привет! Прислушался к твоим рекомендациям, копался в интернете, в ChatGPT, испробовал кучу вариантов реализации и написания кастомных плагинов для Vite. Все сводится к одну готовому решению: `vite-plugin-pwa`, который создает файл манифеста и по совместительсвту из этого же файла сам генерирует sw.js, где настраиват кеширование на статические файлы.

Хорошо, почему нет. Насколько я знаю есть еще workbox is от команды хрома, он не подходит?

2024-10-02 21:25 UTC, merged