Добавил тестирование для реакт компонентов
malcewdeveloper/lazer-overload-yp pull request #77
Opened 2024-09-18 17:05 UTC by JeffChen-png

Тестирование Экрана хода

2024-09-19 13:48 UTC, kyzinatra commented
К сожалению не получится проверить вашу работу, так как нет ни 1 апрува от ваших коллег. Попросите их проверить работу, а после этого сразу присылайте мне на проверку ^_^

2024-09-20 10:01 UTC, malcewdeveloper requested changes
Привет! 
В целом тесты выглядят хорошо, но не могу поставить апрув, у тебя есть ошибка в тестах по node, исправишь ее?

2024-09-23 11:17 UTC, malcewdeveloper approved these changes

2024-09-23 11:20 UTC, chedore approved these changes

2024-09-23 13:11 UTC, kyzinatra commented on packages/client/src/pages/SignIn/__tests__/SignIn.test.tsx
> +        );
Отлично! Хорошее тестирование базовых классов

2024-09-23 13:12 UTC, kyzinatra approved these changes
Отличная работа! Хорошая реализация базовых вариантов тестов. Все запускается, проходит. Стоит конечно делать более подробные тесты для компонентов, но сейчас выглядит вполне хорошо

2024-09-27 16:24 UTC, merged